### ISSUE TITLE
How to reset the setup process?

### ISSUE THREAD

**Issue by seelenfrieden** [Cloudzik1337/SpotifyVolumeControler#2]
Need to enter an new Client ID. How can i do this? Because of the error: INVALID_CLIENT: Invalid redirect URI

**Comment by Cloudzik1337** [comment]
Hi 
I belive you are using exe which is older than py version (my bad)
So simply go to C:\User\username\AppData\Roaming and delete 
spotifyvolumecontrol.app
Now go to your spotify app and change http://localhost/8080 to http://localhost/
Thats should work

**Comment by seelenfrieden** [comment]
thank you! after going through the steps and reinstalled there is still a issue. at step 14 my prompt is: [i] Waiting For Spotify 
and after this the windows closes. and the F6-8 key do not work. have you any idea what i should do?
i tried with http://localhost/ and http://localhost:8080

**Comment by Cloudzik1337** [comment]
Program tries to check if there is instance that is playing music for ex. Your phone or pc so u have to run some music before or while program waits

**Comment by seelenfrieden** [comment]
thanks, that worked. BUT:

[i] Succesyfully Connected To Spotify!
Der Befehl "Clyde" ist entweder falsch geschrieben oderice named DENNIS Volume: 80
konnte nicht gefunden werden.

**Comment by Cloudzik1337** [comment]
Love to hear that!
